### ISSUE TITLE
AuthApplication 启动报错

### ISSUE THREAD

**Issue by 704480904** [azhon/Floret#2]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-05-09 16:04:29.666 ERROR 8008 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in org.azhon.auth.TestController required a bean of type 'org.azhon.user.fegin.UserClient' that could not be found.

Action:

Consider defining a bean of type 'org.azhon.user.fegin.UserClient' in your configuration.

Process finished with exit code 1

**Comment by azhon** [comment]
I'm sorry！ My project is under development，Probably released in June
